telephony_development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: telephony_development
  pool: 5

telephony_test: &TEST
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: telephony_test
  pool: 5

cucumber: *TEST
telephony_cucumber: *TEST

development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: telephony_development
  pool: 5

test: &DUMMY_TEST
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: telephony_test
  pool: 5
